<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Booking;
/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{
    public function addBookingDetails($flightId, $noOfSeats,$userId){

        $em = $this->getEntityManager();
        $booking = new Booking();
        $booking->setFlightId($flightId);
        $booking->setUserId($userId);
        $booking->setSeat($noOfSeats);
        $booking->setCreatedAt(new \DateTime('now'));
        $em->persist($booking);
        $em->flush($booking);
    }
}
