<?php

namespace AppBundle\Repository;

/**
 * tRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tRepository extends \Doctrine\ORM\EntityRepository
{
}
